version: '2'

services:
#  db:
#    build: .
#    volumes:
#      - ./pgdata:/pgdata
#    ports:
#      - "5432:5432"
#    environment:
#      - PGDATA=/pgdata
#      - DB_PORT=:5432
#      - DB_HOST=localhost
#      - DB_USER=postgres
#      - DB_PASSWORD=postgres
#      - DB=postgres

  api:
    build: .
    image: product-microservice:1.0.1
    environment:
    - PORT=:8090
    - DB_PORT=:5432
    - DB_HOST=localhost
    - DB_USER=postgres
    - DB_PASSWORD=postgres
    - DB=postgres
    ports:
    - "8090:8090"
#    links:
#    - db

